# Generated by Django 4.2.7 on 2023-12-03 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('koment', models.TextField()),
                ('name', models.CharField(max_length=30)),
                ('mark', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='maxsulot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('discription', models.TextField()),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('name', models.TextField()),
                ('category', models.CharField(max_length=200)),
                ('date', models.DateField()),
            ],
        ),
    ]
