# Generated by Django 4.2.7 on 2023-11-30 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('koment', models.TextField()),
                ('name', models.CharField(max_length=30)),
                ('mark', models.IntegerField()),
            ],
        ),
    ]
