# Generated by Django 4.2.7 on 2023-12-02 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='mahsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('name', models.TextField()),
                ('category', models.CharField(max_length=200)),
                ('date', models.DateField()),
            ],
        ),
    ]
