# Generated by Django 5.0 on 2023-12-07 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('name', models.TextField()),
                ('category', models.CharField(max_length=200)),
                ('date', models.DateField()),
            ],
        ),
    ]
