# Generated by Django 5.0 on 2023-12-07 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_maxsulot'),
    ]

    operations = [
        migrations.DeleteModel(
            name='maxsulot',
        ),
    ]
