# Generated by Django 5.0 on 2023-12-07 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_delete_maxsulot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='title',
        ),
    ]
