# Generated by Django 5.0 on 2023-12-07 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_name_product_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='title',
            new_name='name',
        ),
    ]
